version: '3.8'
services:
  tomcat:
    build: .
    container_name: tomcat-server
    ports:
      - "8080:8080"  # Porta HTTP
    volumes:
      - ./webapps:/usr/local/tomcat/webapps # Montar o diretório local no container
    restart: always
